version: "3"

tasks:
  install:
    desc: Install all dependencies (Python + Node)
    cmds:
      - venv/bin/pip install -r requirements.txt
      - cd frontend && npm install

  run:backend:
    desc: Start FastAPI backend on port 8000
    cmds:
      - venv/bin/uvicorn backend.app.main:app --reload --port 8000

  run:frontend:
    desc: Start React frontend dev server on port 5173
    dir: frontend
    cmds:
      - npm run dev

  lint:
    desc: Run pre-commit hooks (black, flake8, isort)
    cmds:
      - venv/bin/pre-commit run --all-files

  test:
    desc: Run pytest
    cmds:
      - venv/bin/pytest tests/ -v
